version: "3"
services:
  environment-var-java:
    image: pseudofunc/passing-env-var-java
    environment:
      - RANGE=${RANGE:-5}

#  RANGE=6 docker-compose up -> doesn't work on windows, need to look into it...or switch to linux.
# either one will do.       