FROM alpine
ENTRYPOINT date

# creating a very simple image which uses alpine as base image and on entering
# it executes the date command.

# to build the image
# docker build -t=pseudofunc/alpine_datefinder .
# to see the image,
# docker images

# to run the image
# docker run pseudofunc/alpine_datefinder
# it will create a container as soon as I run.
# docker ps -a